### PR TITLE
feat: 🎸 add time to read for reach text

### PR DESCRIPTION
**Pull request by kitos**
Reference implementation - https://github.com/gatsbyjs/gatsby/blob/29a8c5cce409bd69da1ec8076ff6b9b79729247e/packages/gatsby-transformer-remark/src/extend-node-type.js#L485

### CODE REVIEW

**Comment by kitos** [comment]
Looks like tests are not being run by CI...

**Comment by sbezludny** [comment]
Thanks for the contribution @kitos!

> Looks like tests are not being run by CI...

That's suspicious, here's the result of the build:
https://travis-ci.com/contentful/rich-text/builds/96956623

Or have I missed something, could you elaborate a bit?

**Comment by kitos** [comment]
> That's suspicious, here's the result of the build:
> https://travis-ci.com/contentful/rich-text/builds/96956623

@sbezludny I can't see test file I've edited in there.
Also I didn't managed to run them locally, but I'll try to do it again.

**Comment by sbezludny** [comment]
Thanks a ton, I'll take a look on that.

**Pull request merged**
