### PR TITLE
feat: 🎸 added support for subscript/superscript types

### PR DESCRIPTION
**Pull request by azubanych**
These changes are needed to continue using this feature to the rich-text editor

### CODE REVIEW

**Comment by azubanych** [comment]
Hello, @burakukula.
Could you look into this PR? I've created but I can't assign somebody to look into it and also I see that automatically nobody assigned as a reviewer. Or maybe I've done something incorrectly? I'm not sure who could look into this, could you assign somebody as a reviewer. 
Thanks in advance!

**Comment by azubanych** [comment]
Hello @denkristoffer, 
I'm not sure but maybe you could look into this PR or assign somebody? I need these changes to be able to implement a new feature into the field-editors repository. Or this repo no longer supported?

**Comment by DanweDE** [comment]
Hi @azubanych! Thank you for this PR. Sadly, merging this PR wouldn't just automatically result in support of subscript and superscript in Contentful. This would require some subsequent work by our product team like enabling and testing it in our content APIs and adding support to [the rich text editor itself](https://github.com/contentful/field-editors/tree/master/packages/rich-text). We won't get to this until at least early next year and I can't make any promises that we would get it done around then, but I can talk within our team to see what we can do. cc @malin-sofrone @cribbles

**Comment by azubanych** [comment]
> Hi @azubanych! Thank you for this PR. Sadly, merging this PR wouldn't just automatically result in support of subscript and superscript in Contentful. This would require some subsequent work by our product team like enabling and testing it in our content APIs and adding support to [the rich text editor itself](https://github.com/contentful/field-editors/tree/master/packages/rich-text). We won't get to this until at least early next year and I can't make any promises that we would get it done around then, but I can talk within our team to see what we can do. cc @malin-sofrone @cribbles

@DanweDE Thanks for the feedback. I'm clearly understood what you mean and I have prepared PR for the [rich text](https://github.com/contentful/field-editors/tree/master/packages/rich-text) too. I just need changes from this repo to be able to add changes into rich text. In simple - I just need a new type, I've already added icons for these two functions in [forma 36](https://github.com/contentful/forma-36) and can implement this into rich text. But if this PR will be not merged changes that I will make into rich text will not work. Please let me know what I can do to make it happens faster. I understood that contentful team hasn't planned to add this function this year, that's why I spent my free time to implement this. I've already deployed a customized rich text package into my company contentful space with super/sub script functions and it works, but I would like to implement this into the root and everybody can use - it is not very hard, just a few lines of code :blush:

If you want I can open PR into [rich-text](https://github.com/contentful/field-editors/tree/master/packages/rich-text) and you could review both PR at once to be sure that both changes will be merged at the same time

**Comment by DanweDE** [comment]
> If you want I can open PR into rich-text and you could review both PR at once to be sure that both changes will be merged at the same time

If you have the code already prepared, than this would be great, I'll definitely have a look at it after the holiday break in January and will try to get the team to pick it up as early as possible in the new year.

**Comment by azubanych** [comment]
> > If you want I can open PR into rich-text and you could review both PR at once to be sure that both changes will be merged at the same time
> 
> If you have the code already prepared, than this would be great, I'll definitely have a look at it after the holiday break in January and will try to get the team to pick it up as early as possible in the new year.

Thanks for the answer! I've prepared [PR for the fields-editors](https://github.com/contentful/field-editors/pull/532)

**Comment by yougotwill** [comment]
Hello @DanweDE, what is the status of this PR? I'm interested in also adding support for the `<s>` tag for strikethroughs. @azubanych Just wanted to say thank you for the hard work and appreciate you wanting to share wit the community. 💪

**Comment by phawxby** [comment]
Adding my voice to @yougotwill, the rich text editor is great but missing an awful lot of basic functionality. I know table support is finally coming via #239 but there's a whole lot of other stuff missing; It seems @azubanych has honoured everything you have asked but no progress has been made. 

cc. @DanweDE @cribbles @cezarsmpio

**Comment by th1nkgr33n** [comment]
I'm joining the fellow group of requester. I currently investigate the option to extend the richtext with subscript and superscript as well. So @azubanych already prepared everything and a big thanks to him from us! Good Job. Please go on in review this and this [field-editor](https://github.com/contentful/field-editors/pull/532/files) as well and hopefully I don't need to fork the whole rich-text :D
cc. @DanweDE @denkristoffer @cribbles @malin-sofrone

**Comment by phawxby** [comment]
@azubanych @yougotwill @th1nkgr33n I decided to flex our account manager and got this update a few minutes ago.

> Regarding the superscript / subscript PR, our product team has reviewed it, and says that it looks good... They plan to merge it within the next few weeks, aligning with other moving parts on our end.

**Comment by yougotwill** [comment]
@phawxby Thank you so much! 🙏

**Comment by th1nkgr33n** [comment]
@phawxby Thanks a lot.

Just because I'm curious. I got a little bit deeper into the configuration of the rich text and it seems that there is an underlying validation on the rich text field. Which doesn't allow to add custom nodeTypes. It that correct?
And is this something missing here as well? Because when I disable some Marks, I got a validation as well on sub and sup and it is no longer allowed, because it doesn't appear on this validation screen.

image

**Comment by danielbaercgn** [comment]
> @azubanych @yougotwill @th1nkgr33n I decided to flex our account manager and got this update a few minutes ago.
> 
> > Regarding the superscript / subscript PR, our product team has reviewed it, and says that it looks good... They plan to merge it within the next few weeks, aligning with other moving parts on our end.

Any news on that? We are in joyful anticipation about this feature!

**Comment by azubanych** [comment]
> > @azubanych @yougotwill @th1nkgr33n I decided to flex our account manager and got this update a few minutes ago.
> > > Regarding the superscript / subscript PR, our product team has reviewed it, and says that it looks good... They plan to merge it within the next few weeks, aligning with other moving parts on our end.
> 
> Any news on that? We are in joyful anticipation about this feature!

As for me, this will not be merged - it took a lot of time just to have some response. I'm already forgetting about these changes and from time to time just saw people's comments that remind me that it is still hasn't been any progress.

**Comment by phawxby** [comment]
> > @azubanych @yougotwill @th1nkgr33n I decided to flex our account manager and got this update a few minutes ago.
> > > Regarding the superscript / subscript PR, our product team has reviewed it, and says that it looks good... They plan to merge it within the next few weeks, aligning with other moving parts on our end.
> 
> Any news on that? We are in joyful anticipation about this feature!

I'm going to give our account manager a prod again.

**Comment by phawxby** [comment]
Paraphrasing the response from our account manager, this change is scheduled after the release of table support. Table support was scheduled for early October but that has been pushed back to early November. 

I also enquired about aira-labels for links and the ability to centre text, neither are planned. So if you want/need either of those like we do I suggest making some noise with support and/or your account managers.

**Comment by malin-sofrone** [comment]
Hi folks, this is Malin from Contentful. I know you are all waiting for this to come out. We are very much aware of this. And I want to let you know that we're working to make this happen. It didn't come out just yet as we were expecting it because we encountered some challenges. 

As some of you know, we have updated the slate version to plate and are adding tables. And with the work done for this, we also made some other changes, so we also need to do some adaptations to the originally proposed solution. We can't merge this as is. 
We are already defining the details and evaluating the effort. So I ask for a bit more patience cause you'll see this coming.

**Comment by danielbaercgn** [comment]
> Hi folks, this is Malin from Contentful. I know you are all waiting for superscript/subscript to come out. We are very much aware of this. And I want to let you know that we're working to make this happen. It didn't come out just yet as we were expecting it because we encountered some challenges.
> 
> As some of you know, we have updated the slate version to plate and are adding tables. And with the work done for this, we also made some other changes, so we also need to do some adaptations to the originally proposed solution. We can't merge this as is. We are already defining the details and evaluating the effort. So I ask for a bit more patience cause you'll see this coming.

Any news on this?

**Comment by einarpersson** [comment]
Any news?

**Comment by MayaGillilanContentful** [comment]
Good news! This is now being worked on and will soon be a part of the rich text editor. Since this branch is inaccessible for me, I'm opening a new PR with @azubanych's changes and the merge conflicts resolved, so I'll be closing this one. Thank you for suggesting this and for the work you did on it :)

**Comment by OzzieOrca** [comment]
This appears to have been already implemented by https://github.com/contentful/field-editors/pull/1280 and https://github.com/contentful/rich-text/pull/391:
Screenshot from 2023-06-15 17-48-19

If you still aren't seeing the feature, edit your content model and enable the field formatting options:
Screenshot from 2023-06-15 17-49-10

**Pull request closed without merging**
