### PR TITLE
feat: add table markup support

### PR DESCRIPTION
**Pull request by cribbles**
Adds `TABLE`, `TABLE_ROW` and `TABLE_CELL` types.

`src/schemas/generated` are generated and can be mostly ignored.

### CODE REVIEW

**Review by cezarsmpio — COMMENTED** [review]
What about the table header? Is it going to be a table cell?

**Comment by cribbles** [comment]
@cezarsmpio as stated in standup, table header cell is tbd, we should get some additional feedback from those working on sdks before adding it. We can make a follow-up ticket for implementing that as we won't be starting with it initially

**Review by cezarsmpio — APPROVED** [review]

**Comment by pjaws** [comment]
Does this mean Contentful is adding built-in support for tables in the rich text editor?

**Comment by cezarsmpio** [comment]
Hi @pjaws ! Yes, we are working on it. Sometime this year, stay tuned ;)

**Comment by phawxby** [comment]
@cribbles do you have an ETA on when the editor will support tables?

**Pull request merged**
