### PR TITLE
chore: Add "typings" to RTFM package.json

### PR DESCRIPTION
**Pull request by erikthedeveloper**
Resolves https://github.com/contentful/rich-text/issues/128 

> Using `@contentful/rich-text-from-markdown` with TypeScript causes an error.
> 
> ```
> Could not find a declaration file for module '@contentful/rich-text-from-markdown'. '{PATH}/node_modules/@contentful/rich-text-from-markdown/dist/rich-text-from-markdown.es5.js' implicitly has an 'any' type.
>   Try `npm install @types/contentful__rich-text-from-markdown` if it exists or add a new declaration (.d.ts) file containing `declare module '@contentful/rich-text-from-markdown';`ts(7016)
> ```
> 
> Other packages such as `@contentful/rich-text-react-renderer` do not cause this error and these provide type definitions. This is a bit strange because both are written in TypeScript.

by adding `"typings"` to `package.json` in the same way other `contentful/rich-text` packages do (for example from `rich-text-html-renderer`):

https://github.com/contentful/rich-text/blob/32993445d5333368fce63bb09102588783542310/packages/rich-text-html-renderer/package.json#L3-L5

---

Preview of types in action when making this edit directly in consuming package's `node_modules`

### CODE REVIEW

**Review by guidoblockfi — APPROVED** [review]

**Review by eyko — APPROVED** [review]

**Review by teramotodaiki — APPROVED** [review]
LGTM!

**Comment by juanpasolano** [comment]
So close 🙏  @erikthedeveloper

**Comment by erikthedeveloper** [comment]
1+ year and 3 approvals later.

Thanks for that nudge @juanpasolano 😆 

I just updated with latest `master`. I'll leave this open in case maintainers still want to merge.

**Comment by catdalfonso** [comment]
Going to bring this one up again - can maintainers please update and merge this?  I'm using the workaround in https://github.com/contentful/rich-text/issues/128 but this seems like a trivial fix.

**Review by z0al — APPROVED** [review]
LGTM. Sorry, it took us too long to merge this.

**Comment by z0al** [comment]
The fix was released in `@contentful/rich-text-from-markdown@15.11.2`

**Pull request merged**
